"use strict";
const crypto=require('node:crypto');
const {scanImages,safePath}=require('./media');
const sleep=ms=>new Promise(r=>setTimeout(r,Math.max(0,Number(ms)||0)));
const safeError=e=>String(e?.message||e||'خطأ غير معروف');
function renderTemplate(text,v){return String(text||'').replace(/\{\{recipient\}\}/gi,v.recipient||'').replace(/\{\{phone\}\}/gi,v.phone||'').replace(/\{\{image\}\}/gi,v.image||'').replace(/\{\{date\}\}/gi,v.date||'').replace(/\{\{time\}\}/gi,v.time||'').trim()}
function hashText(v){return crypto.createHash('sha1').update(String(v||''),'utf8').digest('hex').slice(0,16)}
function nowVars(target,image,tz){return {recipient:target.name||'',phone:target.phone||'',image:image?.filename||'',date:new Intl.DateTimeFormat('ar-OM',{timeZone:tz,dateStyle:'short'}).format(new Date()),time:new Intl.DateTimeFormat('ar-OM',{timeZone:tz,hour:'2-digit',minute:'2-digit'}).format(new Date())}}
function key(stage,text,image){return stage==='image'?`image:${image.id}:${image.size||0}`:`${stage}:${hashText(text)}`}
function assertConfirmed(r,label){const a=r?.__chatBotAck;if(a?.status==='pending')throw Object.assign(new Error(`${label}: حالة الإرسال غير مؤكدة؛ لم يُعتمد كمرسل لمنع التكرار.`),{code:'SEND_UNCERTAIN'});return r}
class DeliveryService{
  constructor({store,whatsapp,log}){this.store=store;this.whatsapp=whatsapp;this.log=log;this.busy=new Set()}
  session(id){return this.store.loadSession(id)}
  files(id){const s=this.session(id);return scanImages(this.store.getPaths(id).images,s.settings.maxImageSizeMB).files}
  images(id){return this.files(id).filter(x=>x.isImage)}
  syncCycle(id){const s=this.session(id),imgs=this.images(id),ids=imgs.map(x=>x.id),old=s.cycle.imageOrder||[],current=old[s.cycle.currentIndex];s.cycle.imageOrder=ids;const map={};for(const iid of ids)map[iid]=s.cycle.delivery?.[iid]||{};s.cycle.delivery=map;if(!ids.length)s.cycle.currentIndex=0;else if(current&&ids.includes(current))s.cycle.currentIndex=ids.indexOf(current);else s.cycle.currentIndex=Math.min(Number(s.cycle.currentIndex)||0,ids.length-1);this.store.saveSession(s);return s}
  targets(s,scheduled=false,selected=null){const recipients=s.recipients.filter(x=>x.enabled!==false).map(x=>({...x,kind:'recipient',targetId:x.id}));const groups=(!scheduled||s.settings.scheduledGroupsEnabled)?s.groups.filter(x=>x.enabled!==false).map(x=>({...x,kind:'group',targetId:x.id,phone:''})):[];const all=[...recipients,...groups];if(!selected?.length)return all;const set=new Set(selected);return all.filter(x=>set.has(`${x.kind==='group'?'g':'r'}:${x.id}`)||set.has(x.id))}
  state(s,image,target){s.cycle.delivery=s.cycle.delivery||{};s.cycle.delivery[image.id]=s.cycle.delivery[image.id]||{};const m=s.cycle.delivery[image.id];m[target.targetId]=m[target.targetId]||{pre:false,image:false,post:false,preKey:null,imageKey:null,postKey:null,lastError:null,round:s.cycle.round};return m[target.targetId]}
  done(st,flag,k){return st[flag]===true&&(!st[`${flag}Key`]||st[`${flag}Key`]===k)}
  async retry(fn,label,s,id){let last;for(let i=0;i<Math.max(1,s.settings.retryAttempts);i++){try{return await fn()}catch(e){last=e;if(e.code==='SEND_UNCERTAIN')throw e;if(i+1<Math.max(1,s.settings.retryAttempts)){this.log(id,'WARN',`${label}: إعادة المحاولة ${i+1}`);await sleep(Number(s.settings.retryDelayMs)||800)}}}throw last}
  async sequence(id,target,image,{scheduled=true,preText,postText,countTowardCycle=true}={}){const s=this.session(id),vars=nowVars(target,image,s.settings.timezone),pre=renderTemplate(preText??s.settings.preText,vars),post=renderTemplate(postText??s.settings.postText,vars),p=this.store.getPaths(id),chatId=await this.whatsapp.resolveChatId(id,target),file=image?safePath(p.images,image.filename):null,st=countTowardCycle&&image?this.state(s,image,target):{pre:false,image:false,post:false};if(!image&&!pre&&!post)throw new Error('اكتب رسالة أو اختر ملفًا واحدًا على الأقل.');const preK=image?key('pre',preText??s.settings.preText,image):`text:${hashText(preText??s.settings.preText)}`,imgK=image?key('image','',image):'',postK=image?key('post',postText??s.settings.postText,image):'';try{
    if(pre&&!this.done(st,'pre',preK)){const r=await this.retry(()=>this.whatsapp.sendText(id,chatId,pre,{timeoutMs:s.settings.sendTimeoutMs}),'الرسالة قبل الصورة',s,id);assertConfirmed(r,'قبل الصورة');st.pre=true;st.preKey=preK;s.stats.sentMessages++;if(r.__chatBotAck?.status==='confirmed')s.stats.confirmedAcks++;this.store.saveSession(s);await sleep(s.settings.sendDelayMs)}
    if(image&&!this.done(st,'image',imgK)){const r=await this.retry(()=>this.whatsapp.sendMedia(id,chatId,file,{timeoutMs:s.settings.sendTimeoutMs}),'الوسائط',s,id);assertConfirmed(r,'الوسائط');st.image=true;st.imageKey=imgK;image.isImage?s.stats.sentImages++:s.stats.sentFiles++;if(r.__chatBotAck?.status==='confirmed')s.stats.confirmedAcks++;this.store.saveSession(s);await sleep(s.settings.sendDelayMs)}
    if(post&&!this.done(st,'post',postK)){const r=await this.retry(()=>this.whatsapp.sendText(id,chatId,post,{timeoutMs:s.settings.sendTimeoutMs}),'الرسالة بعد الصورة',s,id);assertConfirmed(r,'بعد الصورة');st.post=true;st.postKey=postK;s.stats.sentMessages++;if(r.__chatBotAck?.status==='confirmed')s.stats.confirmedAcks++;this.store.saveSession(s)}
    return st;
  }catch(e){if(e.code==='SEND_UNCERTAIN')s.stats.uncertainSends++;st.lastError=safeError(e);this.store.saveSession(s);throw e}
  }
  allComplete(s,image,targets){return targets.every(t=>{const st=s.cycle.delivery?.[image.id]?.[t.targetId]||{};const vars=nowVars(t,image,s.settings.timezone),pre=renderTemplate(s.settings.preText,vars),post=renderTemplate(s.settings.postText,vars);return this.done(st,'image',key('image','',image))&&(!pre||this.done(st,'pre',key('pre',s.settings.preText,image)))&&(!post||this.done(st,'post',key('post',s.settings.postText,image)))})}
  advance(id,selected=null,scheduled=true){const s=this.syncCycle(id),imgs=this.images(id),cur=imgs[s.cycle.currentIndex];if(!cur)return false;const targets=this.targets(s,scheduled,selected);if(!targets.length||!this.allComplete(s,cur,targets))return false;if(s.cycle.currentIndex>=imgs.length-1){s.cycle.round++;s.cycle.roundStartedAt=new Date().toISOString();s.cycle.currentIndex=0;s.cycle.delivery={};s.cycle.manualGuard={};this.store.saveSession(s);this.log(id,'INFO',`اكتملت دورة الصور وبدأت الجولة ${s.cycle.round}.`)}else{s.cycle.currentIndex++;this.store.saveSession(s)}return true}
  async scheduledRun(id){const sid=this.store.safeSessionId(id);if(this.busy.has(sid))return {ok:false,message:'يوجد إرسال قيد التنفيذ.'};this.busy.add(sid);try{let s=this.syncCycle(sid);const savedSchedule=Array.isArray(s.settings.scheduleTargets)?s.settings.scheduleTargets.filter(Boolean):[];this.advance(sid,savedSchedule.length?savedSchedule:null,true);s=this.session(sid);const imgs=this.images(sid),image=imgs[s.cycle.currentIndex],targets=this.targets(s,true,savedSchedule.length?savedSchedule:null);if(!image)return {ok:false,retry:false,message:'لا توجد صور.'};if(!targets.length)return {ok:false,retry:false,message:'لا توجد أهداف مفعلة.'};await this.whatsapp.ensureReady(sid);const sent=[],failed=[];for(const t of targets){try{await this.sequence(sid,t,image,{scheduled:true,countTowardCycle:true});sent.push({target:t.name,kind:t.kind,image:image.filename})}catch(e){failed.push({target:t.name,kind:t.kind,error:safeError(e),code:e.code||null});const cur=this.session(sid);cur.stats.failedSends++;this.store.saveSession(cur)}}s=this.session(sid);const complete=this.allComplete(s,image,targets);if(complete)this.advance(sid,savedSchedule.length?savedSchedule:null,true);s=this.session(sid);s.lastRun={at:new Date().toISOString(),type:'scheduled',image:image.filename,round:s.cycle.round,sent,failed,complete};complete?s.stats.successfulRuns++:s.stats.failedRuns++;this.store.saveSession(s);return {ok:failed.length===0,retry:failed.length>0,sent,failed,complete,image:image.filename,round:s.cycle.round}}finally{this.busy.delete(sid)}}
  cleanupManualGuard(s,windowMs){const guard=s.cycle.manualGuard||{};const now=Date.now();for(const [k,v] of Object.entries(guard)){const at=typeof v==='number'?v:Number(v?.at||0);if(!at||now-at>windowMs)delete guard[k]}s.cycle.manualGuard=guard}
  async sendNow(id,{targetKeys=[],targets=[],recipientIds=[],groupIds=[],mediaId,filename,mediaIds=[],beforeText,afterText,preText,postText,sendOrder='target-first',countTowardCycle=false,repeatGuard=true,replaceDuplicate=false}={}){const sid=this.store.safeSessionId(id);if(this.busy.has(sid))throw new Error('يوجد إرسال آخر قيد التنفيذ.');this.busy.add(sid);try{let s=this.session(sid);const files=this.files(sid);const requested=[...(Array.isArray(mediaIds)?mediaIds:[]),mediaId,filename].filter(Boolean).map(String);const wantedIds=[...new Set(requested)];const images=wantedIds.length?wantedIds.map(x=>files.find(f=>f.id===x)).filter(Boolean):[];if(wantedIds.length!==images.length)throw new Error('بعض الملفات المحددة غير موجودة أو تجاوزت الحد المسموح.');const selectedKeys=Array.isArray(targetKeys)&&targetKeys.length?targetKeys:(Array.isArray(targets)&&targets.length?targets:[...recipientIds.map(x=>`r:${x}`),...groupIds.map(x=>`g:${x}`)]);preText=preText??beforeText;postText=postText??afterText;const targetsList=this.targets(s,false,selectedKeys);if(!targetsList.length)throw new Error('حدد مستلمًا أو مجموعة واحدة على الأقل.');if(!images.length&&!String(preText||'').trim()&&!String(postText||'').trim())throw new Error('اكتب رسالة أو اختر ملفًا واحدًا على الأقل.');const windowMs=90000;this.cleanupManualGuard(s,windowMs);this.store.saveSession(s);const sent=[],failed=[];const jobs=[];if(sendOrder==='image-first'&&images.length){for(const image of images)for(const t of targetsList)jobs.push({image,t});}else{for(const t of targetsList){if(images.length)for(const image of images)jobs.push({image,t});else jobs.push({image:null,t});}}
    for(const job of jobs){const {image,t}=job;const fingerprint=crypto.createHash('sha1').update(JSON.stringify([t.targetId,image?.id||'text',preText??s.settings.preText,postText??s.settings.postText]),'utf8').digest('hex');const prev=s.cycle.manualGuard?.[fingerprint];if(repeatGuard&&prev&&!replaceDuplicate){failed.push({target:t.name,kind:t.kind,image:image?.filename||null,error:'تم منع إرسال مطابق خلال آخر 90 ثانية.'});continue}try{await this.sequence(sid,t,image,{scheduled:false,preText,postText,countTowardCycle});sent.push({target:t.name,kind:t.kind,image:image?.filename||null});s=this.session(sid);s.cycle.manualGuard=s.cycle.manualGuard||{};s.cycle.manualGuard[fingerprint]={at:Date.now(),target:t.name,image:image?.filename||null};this.store.saveSession(s)}catch(e){failed.push({target:t.name,kind:t.kind,image:image?.filename||null,error:safeError(e),code:e.code||null});s=this.session(sid);s.stats.failedSends++;this.store.saveSession(s)}}
    return {ok:failed.length===0,sent,failed,images:images.map(x=>x.filename)}
  }finally{this.busy.delete(sid)}}
  currentImage(id){const s=this.syncCycle(id),imgs=this.images(id);return imgs[s.cycle.currentIndex]||imgs[0]||null}
}
module.exports={DeliveryService,renderTemplate,hashText,safeError};
