'use strict';
function normalize(v){return String(v||'').normalize('NFKC').trim().toLocaleLowerCase('ar');}
function normalizeChatId(v){return String(v||'').trim().toLowerCase();}
function idText(v){if(!v)return '';if(typeof v==='string')return v;if(v._serialized)return String(v._serialized);if(v.$1)return String(v.$1);if(v.fromMe!==undefined&&v.remote&&v.id)return `${Boolean(v.fromMe)}_${v.remote}_${v.id}`;return String(v.serialized||v.id||'').trim();}
function chatIdFromReaction(reaction){const key=reaction?.msgId||reaction?.id||{};return normalizeChatId(reaction?.chatId||key.remote||key.$2||key._serialized?.split?.('_')?.slice?.(1,-1)?.join?.('_')||'');}
function minutesOf(time){const m=String(time||'').match(/^(\d{2}):(\d{2})$/);if(!m)return null;const h=Number(m[1]),min=Number(m[2]);return h>23||min>59?null:h*60+min;}
function quietHoursActive(settings,now=new Date()){if(!settings?.interactionQuietEnabled)return false;const start=minutesOf(settings.interactionQuietStart),end=minutesOf(settings.interactionQuietEnd);if(start==null||end==null||start===end)return false;const parts=new Intl.DateTimeFormat('en-GB',{timeZone:settings.timezone||'Asia/Muscat',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(now);const current=Number(parts.find(x=>x.type==='hour')?.value||0)*60+Number(parts.find(x=>x.type==='minute')?.value||0);return start<end?current>=start&&current<end:current>=start||current<end;}
function scopeAllowed(scope,chatId,selectedIds=[]){const id=normalizeChatId(chatId);const group=id.endsWith('@g.us');if(scope==='groups')return group;if(scope==='private')return !group;if(scope==='selected')return selectedIds.map(normalizeChatId).filter(Boolean).includes(id);return true;}
function matchRule(rule,event,text,emoji){if(rule.when.type!==event)return false;const input=normalize(event==='reaction'?emoji:text),value=normalize(rule.when.value);switch(rule.when.match){case'any':return Boolean(input);case'exact':return Boolean(value)&&input===value;case'contains':return Boolean(value)&&input.includes(value);case'starts':return Boolean(value)&&input.startsWith(value);case'ends':return Boolean(value)&&input.endsWith(value);case'regex':if(!value)return false;try{return new RegExp(rule.when.value,rule.when.ignoreCase===false?'u':'iu').test(event==='reaction'?emoji:text)}catch{return false;}default:return false;}}
function validateRule(rule){if(!['message','reaction'].includes(rule.when.type))throw new Error('نوع الحدث غير مدعوم.');if(!['any','contains','exact','starts','ends','regex'].includes(rule.when.match))throw new Error('نوع المطابقة غير مدعوم.');if(rule.when.match!=='any'&&!String(rule.when.value||'').trim())throw new Error('اكتب القيمة التي سيبحث عنها البوت.');if(rule.when.match==='regex'){try{new RegExp(rule.when.value,rule.when.ignoreCase===false?'u':'iu')}catch{throw new Error('تعبير Regex غير صالح.');}}if(!['all','private','groups','selected'].includes(rule.scope||'all'))throw new Error('نطاق القاعدة غير مدعوم.');if(rule.scope==='selected'&&(!Array.isArray(rule.chatIds)||!rule.chatIds.length))throw new Error('عند اختيار «محدد فقط» يجب إضافة معرف محادثة أو مجموعة واحدة على الأقل.');if(!rule.then.reply&&!rule.then.reaction)throw new Error('اختر ردًا أو Reaction.');return true;}
function render(text,ctx,timezone='Asia/Muscat'){const now=new Date(),time=new Intl.DateTimeFormat('ar-OM',{timeZone:timezone,hour:'2-digit',minute:'2-digit'}).format(now);return String(text||'').replace(/\{\{message\}\}/gi,String(ctx.message||'')).replace(/\{\{sender\}\}/gi,String(ctx.sender||'صديق')).replace(/\{\{time\}\}/gi,time).replace(/\{\{chat\}\}/gi,String(ctx.chat||'')).replace(/\{\{type\}\}/gi,String(ctx.type||'')).replace(/\{\{emoji\}\}/gi,String(ctx.emoji||'')).trim();}
class InteractionEngine{
  constructor({store,whatsapp,log}){this.store=store;this.whatsapp=whatsapp;this.log=log;this.cooldowns=new Map();this.rate=new Map();this.seen=new Map();this.inFlight=new Set();}
  rateOk(id,limit){const now=Date.now();let b=this.rate.get(id);if(!b||now-b.start>=60000){b={start:now,count:0};this.rate.set(id,b);}if(b.count>=limit)return false;b.count+=1;return true;}
  remember(key){this.seen.set(key,Date.now());if(this.seen.size>5000){const cutoff=Date.now()-10*60*1000;for(const[k,t]of this.seen)if(t<cutoff)this.seen.delete(k);}}
  cleanup(){const now=Date.now();for(const[k,t]of this.seen)if(t<now-10*60*1000)this.seen.delete(k);for(const[k,t]of this.cooldowns)if(t<now-7*24*60*60*1000)this.cooldowns.delete(k);}
  globalScopeAllowed(s,chatId){return scopeAllowed(s.settings.interactionScope||s.interaction.scope||'all',chatId,s.settings.interactionChatIds||s.interaction.chatIds||[]);}
  async handle(id,event,raw){
    const s=this.store.loadSession(id);if(!s.interaction.enabled||!s.settings.interactionEnabled)return;if(event==='reaction'&&(raw?.fromMe||raw?.author?.fromMe||raw?.senderId?.fromMe))return;if(quietHoursActive(s.settings))return;
    const chatId=event==='message'?normalizeChatId(raw?.from||raw?.chatId||raw?.to):chatIdFromReaction(raw);if(!chatId||!this.globalScopeAllowed(s,chatId))return;if(event==='message'&&s.interaction.ignoreOwnMessages!==false&&raw?.fromMe)return;
    const text=event==='message'?String(raw?.body||''):'',emoji=event==='reaction'?String(raw?.reaction||''):'';const msgId=event==='message'?idText(raw?.id):idText(raw?.msgId||raw?.id);const stableId=msgId||`${event}|${chatId}|${String(raw?.timestamp||'')}|${text}|${emoji}`;const seenKey=`${event}|${stableId}|${chatId}|${text}|${emoji}`;if(this.seen.has(seenKey))return;this.remember(seenKey);
    const rules=[...s.interaction.rules].filter(r=>r.enabled!==false).sort((a,b)=>Number(b.priority||0)-Number(a.priority||0));
    for(const rule of rules){if(!scopeAllowed(rule.scope||s.settings.interactionScope||'all',chatId,rule.chatIds||[]))continue;if(!matchRule(rule,event,text,emoji))continue;const key=`${id}|${rule.id}|${chatId}`;const cooldown=Math.min(Number(rule.cooldownSec||0),Number(s.settings.interactionCooldownCapSec||86400));if(Date.now()-(this.cooldowns.get(key)||0)<cooldown*1000)continue;if(this.inFlight.has(key))continue;try{validateRule(rule)}catch(error){this.record(s,id,event,rule,'error',chatId,text,emoji,error);continue;}if(!this.rateOk(`${id}|${chatId}`,s.settings.maxActionsPerMinute))return;this.inFlight.add(key);
      try{const sender=String(raw?.notifyName||raw?._data?.notifyName||'صديق'),ctx={message:text,sender,chat:chatId,type:event,emoji},reply=render(rule.then.reply,ctx,s.settings.timezone);if(reply){if(event==='message')await this.whatsapp.replyToMessage(id,raw,reply);else await this.whatsapp.sendText(id,chatId,reply,{observeAck:true});}if(rule.then.reaction&&msgId)await this.whatsapp.reactToMessage(id,raw?.id||msgId,rule.then.reaction);this.cooldowns.set(key,Date.now());this.record(s,id,event,rule,'success',chatId,text,emoji,null);}
      catch(error){this.record(s,id,event,rule,error?.code==='SEND_UNCERTAIN'?'uncertain':'error',chatId,text,emoji,error);this.log(id,error?.code==='SEND_UNCERTAIN'?'WARN':'ERROR',`فشل التفاعل «${rule.name}»: ${safe(error)}`)}finally{this.inFlight.delete(key)}
      if(rule.then.stopAfter!==false)break;
    }
    this.cleanup();
  }
  record(base,id,event,rule,status,chatId,text,emoji,error){const s=this.store.loadSession(id);s.interaction.recent=[...s.interaction.recent,{at:new Date().toISOString(),event,ruleId:rule.id,status,chatId,text:String(text||'').slice(0,250),emoji,detail:error?safe(error):undefined}].slice(-200);if(status==='success')s.stats.interactionActions+=1;else s.stats.interactionErrors+=1;this.store.saveSession(s);}
  onMessage(id,message){return this.handle(id,'message',message)}
  onReaction(id,reaction){return this.handle(id,'reaction',reaction)}
}
function safe(error){return String(error?.message||error||'خطأ غير معروف')}
module.exports={InteractionEngine,matchRule,validateRule,idText,chatIdFromReaction,quietHoursActive,minutesOf,scopeAllowed,render};
