"use strict";
const fs=require('node:fs');
const path=require('node:path');
const IMAGE_EXT=new Set(['.jpg','.jpeg','.png','.webp','.gif']);
const MEDIA_EXT=new Set([...IMAGE_EXT,'.pdf','.txt','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.zip','.mp4','.mp3','.m4a','.ogg','.wav']);
const MIME={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.gif':'image/gif','.pdf':'application/pdf','.txt':'text/plain','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xls':'application/vnd.ms-excel','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.ppt':'application/vnd.ms-powerpoint','.pptx':'application/vnd.openxmlformats-officedocument.presentationml.presentation','.zip':'application/zip','.mp4':'video/mp4','.mp3':'audio/mpeg','.m4a':'audio/mp4','.ogg':'audio/ogg','.wav':'audio/wav'};
function safeName(v){const base=path.basename(String(v||''));if(!base||base==='.'||base==='..')throw new Error('اسم ملف غير صالح.');return base}
function safePath(dir,name){const n=safeName(name),p=path.resolve(dir,n),root=path.resolve(dir)+path.sep;if(p!==path.resolve(dir)&&!p.startsWith(root))throw new Error('مسار ملف غير آمن.');return p}
function imageNumber(name){const m=String(name).match(/^img\.(\d+)(\.[A-Za-z0-9]+)$/i);return m?Number(m[1]):0}
function nextImageName(dir,ext){fs.mkdirSync(dir,{recursive:true});const used=new Set(fs.readdirSync(dir).map(imageNumber).filter(Boolean));let n=1;while(used.has(n))n++;return `img.${n}${String(ext||'.png').toLowerCase()}`}
function uniqueFileName(dir,base,ext){fs.mkdirSync(dir,{recursive:true});const clean=String(base||'file').replace(/[^\w\-.\u0600-\u06ff ]/g,'_').trim().slice(0,70)||'file';const stamp=`${Date.now()}_${Math.random().toString(36).slice(2,7)}`;let name=`${clean}_${stamp}${ext}`;let i=2;while(fs.existsSync(safePath(dir,name))){name=`${clean}_${stamp}_${i++}${ext}`}return name}
function scan(dir,maxMB=20){fs.mkdirSync(dir,{recursive:true});const all=[],bad=[];for(const f of fs.readdirSync(dir,{withFileTypes:true})){if(!f.isFile())continue;const ext=path.extname(f.name).toLowerCase(),full=path.join(dir,f.name);let st;try{st=fs.statSync(full)}catch{continue}if(!MEDIA_EXT.has(ext)){bad.push({filename:f.name,error:'نوع غير مدعوم'});continue}if(st.size>maxMB*1024*1024){bad.push({filename:f.name,error:'الحجم أكبر من الحد'});continue}all.push({id:f.name,filename:f.name,ext,size:st.size,updatedAt:st.mtime.toISOString(),isImage:IMAGE_EXT.has(ext)});}all.sort((a,b)=>{const an=imageNumber(a.filename),bn=imageNumber(b.filename);return an||bn?an-bn:a.filename.localeCompare(b.filename)});return {files:all,images:all.filter(x=>x.isImage),invalid:bad,duplicates:[]}}
module.exports={IMAGE_EXT,MEDIA_EXT,MIME,safeName,safePath,imageNumber,nextImageName,uniqueFileName,scan,scanImages:scan};
